-- Insert 100 job announcements across 4 eco-friendly categories
INSERT INTO public.job_announcements (title, description, category, price, location, is_promoted, created_at)
VALUES
-- Reciclare (25 jobs)
('Operator Centru Reciclare', 'Lucrează la sortarea și procesarea materialelor reciclabile', 'Reciclare', '2500 - 3000 RON', 'București', false, NOW() - INTERVAL '30 days'),
('Inginer Mediu Reciclare', 'Supervizează operații de reciclare și optimizează procese', 'Reciclare', '4000 - 5000 RON', 'Cluj-Napoca', false, NOW() - INTERVAL '29 days'),
('Colector Deșeuri Selecte', 'Colectare și transport de deșeuri reciclabile', 'Reciclare', '2200 - 2800 RON', 'Brașov', false, NOW() - INTERVAL '28 days'),
('Specialist Compostare', 'Gestionare a procesului de compostare și biodecompunere', 'Reciclare', '2700 - 3200 RON', 'Iași', false, NOW() - INTERVAL '27 days'),
('Operator Instalaţie Plastic', 'Prelucrare plastice reciclate pentru producția noilor articole', 'Reciclare', '2600 - 3100 RON', 'Timișoara', false, NOW() - INTERVAL '26 days'),
('Manager Proiect Reciclare', 'Coordonează proiecte de reciclare pe scară largă', 'Reciclare', '3500 - 4500 RON', 'București', true, NOW() - INTERVAL '25 days'),
('Tehnician Ambalaje Eco', 'Dezvoltare și testare ambalaje biodegradabile', 'Reciclare', '3000 - 3800 RON', 'Constanța', false, NOW() - INTERVAL '24 days'),
('Investigator Deșeuri', 'Audit și investigare procese de reciclare', 'Reciclare', '3200 - 4000 RON', 'Galați', false, NOW() - INTERVAL '23 days'),
('Operator Presă Reciclare', 'Operare echipamente de presare și compactare deșeuri', 'Reciclare', '2300 - 2900 RON', 'Pitești', false, NOW() - INTERVAL '22 days'),
('Specialist Marketing Eco', 'Promovare programe de reciclare și educație ecologică', 'Reciclare', '2800 - 3500 RON', 'București', false, NOW() - INTERVAL '21 days'),
('Chimist Tratament Apă', 'Tratarea apelor uzate din procese de reciclare', 'Reciclare', '3300 - 4200 RON', 'Craiova', false, NOW() - INTERVAL '20 days'),
('Conducător Vehicol Colectare', 'Transport deșeuri selecte cu mașini specializate', 'Reciclare', '2400 - 3000 RON', 'Sibiu', false, NOW() - INTERVAL '19 days'),
('Asistent Laborator Reciclare', 'Testare calitate materiale reciclate', 'Reciclare', '2000 - 2600 RON', 'Arad', false, NOW() - INTERVAL '18 days'),
('Designer Packaging Sustenabil', 'Creație ambalaje eco-friendly inovatoare', 'Reciclare', '3600 - 4500 RON', 'Cluj-Napoca', true, NOW() - INTERVAL '17 days'),
('Supervizor Instalație', 'Supravegheaza instalații de reciclare', 'Reciclare', '3100 - 3900 RON', 'Constanța', false, NOW() - INTERVAL '16 days'),
('Mecanic Echipamente Reciclare', 'Reparație și întreținere echipamente', 'Reciclare', '2900 - 3600 RON', 'Dolj', false, NOW() - INTERVAL '15 days'),
('Educatoare Programe Reciclare', 'Educație în comunități privind reciclarea', 'Reciclare', '2500 - 3200 RON', 'Bihor', false, NOW() - INTERVAL '14 days'),
('Vânzător Produse Reciclate', 'Vânzare produse fabricate din materiale reciclate', 'Reciclare', '2200 - 2800 RON', 'Satu Mare', false, NOW() - INTERVAL '13 days'),
('Specialist Logistică Reciclare', 'Optimizare rute transport și depozitare deșeuri', 'Reciclare', '3000 - 3800 RON', 'Bacău', false, NOW() - INTERVAL '12 days'),
('Operator Control Calitate', 'Verificare și evaluare materiale reciclate', 'Reciclare', '2600 - 3200 RON', 'Vaslui', false, NOW() - INTERVAL '11 days'),
('Director Program Reciclare', 'Conducere program reciclare integrat', 'Reciclare', '5000 - 6500 RON', 'București', true, NOW() - INTERVAL '10 days'),
('Inginer Proces Reciclare', 'Optimizare procese și flux de producție', 'Reciclare', '3800 - 4800 RON', 'Ploiești', false, NOW() - INTERVAL '9 days'),
('Operator Sortare Manuală', 'Sortare deșeuri conform standardelor', 'Reciclare', '2100 - 2700 RON', 'Buzău', false, NOW() - INTERVAL '8 days'),
('Tehnician Reparații', 'Reparare și restabilire echipamente', 'Reciclare', '2800 - 3400 RON', 'Hunedoara', false, NOW() - INTERVAL '7 days'),
('Auditor Mediu Reciclare', 'Audit conformitate și standarde mediu', 'Reciclare', '3400 - 4300 RON', 'Timiș', false, NOW() - INTERVAL '6 days'),

-- Energie (25 jobs)
('Installer Panouri Solare', 'Instalare sisteme fotovoltaice pe acoperișuri', 'Energie', '3000 - 3800 RON', 'București', false, NOW() - INTERVAL '30 days'),
('Inginer Energii Regenerabile', 'Proiectare sisteme energie verde', 'Energie', '4200 - 5500 RON', 'Cluj-Napoca', true, NOW() - INTERVAL '29 days'),
('Electrician Sistem Solar', 'Electricitate pentru instalații solare', 'Energie', '2800 - 3500 RON', 'Brașov', false, NOW() - INTERVAL '28 days'),
('Tehnician Turbine Vânt', 'Montaj și reparație turbine eoliene', 'Energie', '3500 - 4500 RON', 'Constanța', false, NOW() - INTERVAL '27 days'),
('Specialist Eficiență Energetică', 'Audit și optimizare consum energetic', 'Energie', '3200 - 4000 RON', 'Iași', false, NOW() - INTERVAL '26 days'),
('Manager Proiect Energie Verde', 'Coordonație proiecte energie regenerabilă', 'Energie', '4000 - 5200 RON', 'Timișoara', true, NOW() - INTERVAL '25 days'),
('Technician Baterie Stocare', 'Instalare sisteme baterii pentru stocare energie', 'Energie', '3100 - 3900 RON', 'București', false, NOW() - INTERVAL '24 days'),
('Inginer Hidro', 'Proiecte centrale hidroelectrice mici', 'Energie', '4300 - 5500 RON', 'Pitești', false, NOW() - INTERVAL '23 days'),
('Operator Centrală Biomasa', 'Operare instalații de încălzire cu biomasa', 'Energie', '2600 - 3300 RON', 'Sibiu', false, NOW() - INTERVAL '22 days'),
('Consultant Energie', 'Consultanță privind energia regenerabilă', 'Energie', '3500 - 4500 RON', 'Cluj-Napoca', false, NOW() - INTERVAL '21 days'),
('Electrician LED', 'Instalare sisteme iluminare LED eficiente', 'Energie', '2500 - 3200 RON', 'Constanța', false, NOW() - INTERVAL '20 days'),
('Operator Panouri Termice', 'Montaj și operare sisteme solare termice', 'Energie', '2700 - 3400 RON', 'Craiova', false, NOW() - INTERVAL '19 days'),
('Inginer Control Energie', 'Monitorizare și control sisteme energetice', 'Energie', '3300 - 4200 RON', 'București', false, NOW() - INTERVAL '18 days'),
('Tehnician Pompe Căldură', 'Instalare și servicii pompe căldură', 'Energie', '2900 - 3700 RON', 'Arad', false, NOW() - INTERVAL '17 days'),
('Sales Energy Systems', 'Vânzare sisteme energie regenerabilă', 'Energie', '2800 - 3600 RON', 'Brașov', false, NOW() - INTERVAL '16 days'),
('Inspector Calitate Instalații', 'Control calitate instalații energetice', 'Energie', '3000 - 3800 RON', 'Galați', false, NOW() - INTERVAL '15 days'),
('Proiectant CAD Energie', 'Proiectare asistate sisteme energetice', 'Energie', '3200 - 4100 RON', 'Cluj-Napoca', false, NOW() - INTERVAL '14 days'),
('Operator Microcentrală', 'Operare microcentrală hidroelectrică', 'Energie', '2400 - 3100 RON', 'Suceava', false, NOW() - INTERVAL '13 days'),
('Specialist Performanță Energetică', 'Certificare și audit performanță', 'Energie', '3400 - 4300 RON', 'Iași', false, NOW() - INTERVAL '12 days'),
('Manager Instalații Solare', 'Gestionare flote panouri solare', 'Energie', '3800 - 4800 RON', 'Timișoara', true, NOW() - INTERVAL '11 days'),
('Electrician Industrial Verde', 'Sisteme electrice pentru industriă eco', 'Energie', '3000 - 3800 RON', 'Constanța', false, NOW() - INTERVAL '10 days'),
('Inginer Sistem Stocare', 'Proiectare sisteme stocare energie', 'Energie', '4100 - 5300 RON', 'București', false, NOW() - INTERVAL '9 days'),
('Operator Stație Biogaz', 'Operare instalație producție biogaz', 'Energie', '2800 - 3500 RON', 'Dolj', false, NOW() - INTERVAL '8 days'),
('Inspecteur Siguranță Energetică', 'Inspecții de siguranță sisteme energetice', 'Energie', '3200 - 4100 RON', 'Cluj-Napoca', false, NOW() - INTERVAL '7 days'),
('Director Strategie Energie', 'Conducere strategie energie regenerabilă', 'Energie', '5200 - 6800 RON', 'București', true, NOW() - INTERVAL '6 days'),

-- Comunitate (25 jobs)
('Organizator Evenimente Eco', 'Organizare activități și workshopuri ecologice', 'Comunitate', '2400 - 3100 RON', 'București', false, NOW() - INTERVAL '30 days'),
('Coordonator Voluntari', 'Coordonare programe voluntariat ecologic', 'Comunitate', '2600 - 3400 RON', 'Cluj-Napoca', false, NOW() - INTERVAL '29 days'),
('Educator Ambiental', 'Educație și sensibilizare față de mediu', 'Comunitate', '2500 - 3200 RON', 'Brașov', true, NOW() - INTERVAL '28 days'),
('Manager Programe Comunitate', 'Conducere programe de implicare comunității', 'Comunitate', '3200 - 4200 RON', 'Iași', false, NOW() - INTERVAL '27 days'),
('Community Liaison Officer', 'Legătură între comunitate și organizații', 'Comunitate', '2700 - 3500 RON', 'Constanța', false, NOW() - INTERVAL '26 days'),
('Animator Cultural Eco', 'Animație și activități ecologice pentru copii', 'Comunitate', '2200 - 2900 RON', 'Timișoara', false, NOW() - INTERVAL '25 days'),
('Specialist Comunicare', 'Comunicare și advocacy pentru cauze eco', 'Comunitate', '2800 - 3600 RON', 'București', false, NOW() - INTERVAL '24 days'),
('Director Centru Comunitate', 'Conducere centru ecologic comunitar', 'Comunitate', '4000 - 5200 RON', 'Cluj-Napoca', true, NOW() - INTERVAL '23 days'),
('Asistent Social Eco', 'Suport social în programe de mediu', 'Comunitate', '2300 - 3000 RON', 'Craiova', false, NOW() - INTERVAL '22 days'),
('Facilitator Workshop', 'Facilitare ateliere și sesiuni educative', 'Comunitate', '2400 - 3100 RON', 'Galați', false, NOW() - INTERVAL '21 days'),
('Officer Parteneriate', 'Dezvoltare parteneriate cu ONG-uri', 'Comunitate', '2900 - 3700 RON', 'Sibiu', false, NOW() - INTERVAL '20 days'),
('Documentator Social', 'Documentare și raportare activități comunitate', 'Comunitate', '2500 - 3200 RON', 'Constanța', false, NOW() - INTERVAL '19 days'),
('Terapeut în Natură', 'Programe terapeutice în natură și comunitate', 'Comunitate', '2700 - 3500 RON', 'Buzău', false, NOW() - INTERVAL '18 days'),
('Recruiter Voluntari', 'Recrutare și selecție voluntari ecologici', 'Comunitate', '2600 - 3300 RON', 'Ploiești', false, NOW() - INTERVAL '17 days'),
('Officer Integrare', 'Integrare comunități în programe eco', 'Comunitate', '2800 - 3600 RON', 'Bacău', false, NOW() - INTERVAL '16 days'),
('Specialist Relații Publice', 'Relații publice și media pentru inițiative eco', 'Comunitate', '3000 - 3900 RON', 'Arad', false, NOW() - INTERVAL '15 days'),
('Coordonator Proiecte Locale', 'Coordonare proiecte de mediu local', 'Comunitate', '2900 - 3700 RON', 'Hunedoara', false, NOW() - INTERVAL '14 days'),
('Mentor Ecologic', 'Mentorat și coaching pentru activități eco', 'Comunitate', '2500 - 3200 RON', 'Satu Mare', false, NOW() - INTERVAL '13 days'),
('Vorbitor Public', 'Prezentări și conferințe pentru cauze ecologice', 'Comunitate', '2700 - 3500 RON', 'Timiș', false, NOW() - INTERVAL '12 days'),
('Administrator Forum Online', 'Gestionare comunități online ecologice', 'Comunitate', '2200 - 2900 RON', 'Vaslui', false, NOW() - INTERVAL '11 days'),
('Coordinator Sănătate Comunitate', 'Programe de sănătate legat de mediu', 'Comunitate', '2800 - 3600 RON', 'Dolj', false, NOW() - INTERVAL '10 days'),
('Manager Parteneriate', 'Gestionare parteneriate și colaborări', 'Comunitate', '3400 - 4400 RON', 'Cluj-Napoca', false, NOW() - INTERVAL '9 days'),
('Lead Dezvoltare Comunitate', 'Lider în dezvoltarea inițiativelor comunitare', 'Comunitate', '3800 - 4900 RON', 'București', true, NOW() - INTERVAL '8 days'),
('Specialist Inkluziune', 'Programe inkluzive pentru toți membrii comunității', 'Comunitate', '2700 - 3500 RON', 'Iași', false, NOW() - INTERVAL '7 days'),
('Chief Community Officer', 'Conducere officer comunitate', 'Comunitate', '4800 - 6300 RON', 'București', true, NOW() - INTERVAL '6 days'),

-- Echilibru Personal (25 jobs)
('Instructor Yoga Natură', 'Yoga și meditație în mediul natural', 'Echilibru Personal', '2300 - 3000 RON', 'București', false, NOW() - INTERVAL '30 days'),
('Wellness Coach Eco', 'Coaching pentru stil de viață sustenabil și sănătos', 'Echilibru Personal', '2800 - 3600 RON', 'Cluj-Napoca', true, NOW() - INTERVAL '29 days'),
('Nutriționist Bio', 'Consiliere nutriție cu produse bio și locale', 'Echilibru Personal', '3000 - 3900 RON', 'Brașov', false, NOW() - INTERVAL '28 days'),
('Terapeut Holistico', 'Terapii holistice cu focus pe mediu', 'Echilibru Personal', '3200 - 4100 RON', 'Constanța', false, NOW() - INTERVAL '27 days'),
('Instructor Fitnes Eco', 'Antrenamente în natură și outdoor', 'Echilibru Personal', '2500 - 3200 RON', 'Iași', false, NOW() - INTERVAL '26 days'),
('Gardener Terapeutic', 'Cultivare plante și terapie prin grădină', 'Echilibru Personal', '2400 - 3100 RON', 'Timișoara', false, NOW() - INTERVAL '25 days'),
('Counselor Stres Eco', 'Consiliere pentru gestionarea stresului prin natură', 'Echilibru Personal', '2900 - 3700 RON', 'București', false, NOW() - INTERVAL '24 days'),
('Chef Organic', 'Gătire cu ingrediente organice și locale', 'Echilibru Personal', '3300 - 4300 RON', 'Cluj-Napoca', true, NOW() - INTERVAL '23 days'),
('Sleep Consultant Bio', 'Consultanță somn cu produse naturale', 'Echilibru Personal', '2700 - 3500 RON', 'Craiova', false, NOW() - INTERVAL '22 days'),
('Psiholog Ambiental', 'Psihologie și relație cu mediul natural', 'Echilibru Personal', '3400 - 4400 RON', 'Sibiu', false, NOW() - INTERVAL '21 days'),
('Instructor Tai Chi Natură', 'Tai Chi și martial arts în aer liber', 'Echilibru Personal', '2400 - 3100 RON', 'Constanța', false, NOW() - INTERVAL '20 days'),
('Life Coach Sustenabil', 'Coaching pentru viață sustenabilă', 'Echilibru Personal', '3100 - 4000 RON', 'Galați', false, NOW() - INTERVAL '19 days'),
('Maseur Naturist', 'Masaj cu uleiuri naturale și ecologice', 'Echilibru Personal', '2600 - 3400 RON', 'Bacău', false, NOW() - INTERVAL '18 days'),
('Instructor Pilates Bio', 'Pilates cu focus pe echilibru natural', 'Echilibru Personal', '2500 - 3200 RON', 'Arad', false, NOW() - INTERVAL '17 days'),
('Consultant Somn Natural', 'Optimizare somn cu metode naturale', 'Echilibru Personal', '2800 - 3600 RON', 'Buzău', false, NOW() - INTERVAL '16 days'),
('Acupunctori Eco', 'Acupunctură și tratamente naturale', 'Echilibru Personal', '3200 - 4100 RON', 'Ploiești', false, NOW() - INTERVAL '15 days'),
('Instructor Meditație', 'Meditație și mindfulness în grup', 'Echilibru Personal', '2300 - 3000 RON', 'Cluj-Napoca', false, NOW() - INTERVAL '14 days'),
('Chef Vegan', 'Gătire vegan și plant-based cu ingrediente eco', 'Echilibru Personal', '3000 - 3900 RON', 'Suceava', false, NOW() - INTERVAL '13 days'),
('Herborist', 'Plante medicinale și remedii naturale', 'Echilibru Personal', '2700 - 3500 RON', 'Iași', false, NOW() - INTERVAL '12 days'),
('Fitness Trainer Natură', 'Antrenament personalizat în aer liber', 'Echilibru Personal', '2800 - 3600 RON', 'Constanța', false, NOW() - INTERVAL '11 days'),
('Specialist Wellness', 'Program wellness complet și integrat', 'Echilibru Personal', '3400 - 4400 RON', 'București', false, NOW() - INTERVAL '10 days'),
('Instructor Dancă Ecologică', 'Dansă cu mesaj ecologic și conectare natură', 'Echilibru Personal', '2500 - 3200 RON', 'Brașov', false, NOW() - INTERVAL '9 days'),
('Director Spa Eco', 'Conducere spa și centru wellness ecologic', 'Echilibru Personal', '4200 - 5400 RON', 'Cluj-Napoca', true, NOW() - INTERVAL '8 days'),
('Consultant Sănătate Holistică', 'Consultanță sănătate din perspective holistice', 'Echilibru Personal', '3600 - 4600 RON', 'Timișoara', false, NOW() - INTERVAL '7 days'),
('Chief Wellness Officer', 'Conducere strategie wellness și echilibru', 'Echilibru Personal', '5000 - 6500 RON', 'București', true, NOW() - INTERVAL '6 days');
